--- #YAML:1.0
name:               Acme-Pythonic
version:            0.47
abstract:           Python whitespace conventions for Perl
author:
    - Xavier Noria (FXN)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Filter::Simple:  0.78
    Test::More:      0.45
    Text::Tabs:      98.112801
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
